onboarding = false

[terminal]
default_shell = "/usr/local/bin/fish"

[keys]
prefix = "ctrl+a"

[theme]
name = "vesper"

[ui.toast]
delivery = "system"

[ui]
show_agent_labels_on_pane_borders = true

agent_panel_sort = "spaces"
[experimental]
allow_nested = true
kitty_graphics = true
