# architect: true
model: openrouter/google/gemini-2.5-pro-preview-03-25
# model: openrouter/qwen/qwq-32b:free
# editor-model: qwen/qwen2.5-coder-7b-instruct
# editor-model: openrouter/qwen/qwen-2.5-coder-32b-instruct:free
