set-option -g status "on"

# default statusbar color
set -g status-bg default
set-option -g status-style bg=default


# default window title colors
set-window-option -g window-status-style bg="#ebbcba",fg="#1F1F28" # bg=yellow, fg=bg1

# default window with an activity alert
set-window-option -g window-status-activity-style bg="#1F1F28",fg=red # bg=bg1, fg=fg3

# active window title colors
set-window-option -g window-status-current-style bg=red,fg="#1F1F28" # fg=bg1

# pane border
set-option -g pane-active-border-style fg="#ebbcba" #fg2
set-option -g pane-border-style fg="#1F1F28" #bg1

# message infos
set-option -g message-style bg="#191724",fg="#e0def4" # bg=bg2, fg=fg1

# writing commands inactive
set-option -g message-command-style bg="#191724",fg="#e0def4" # bg=fg3, fg=bg1

# pane number display
set-option -g display-panes-active-colour "#ebbcba" #fg2
set-option -g display-panes-colour "#1F1F28" #bg1

# Theme settings mixed with colors (unfortunately, but there is no cleaner way)
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left "#[bg=#9ccfd8,fg=#191724] #S #[bg=#191724, fg=#9ccfd8]"
set-option -g status-right ""

set-window-option -g window-status-current-format "#[bg=#ebbcba,fg=#1F1F28,nobold,noitalics,nounderscore]#[bg=#ebbcba,fg=#191724,bold] #W#{?window_zoomed_flag,*Z,} #[bg=#1F1F28,fg=#ebbcba,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#191724,fg=#191724,noitalics]#[bg=#191724,fg=#e0def4] #W #[bg=#191724,fg=#191724,noitalics]"
