set-option -g status "on"

# default statusbar color
set status-bg "#181616"

# default window title colors
set-window-option -g window-status-style bg="#c4746e",fg="#181616" # bg=yellow, fg=bg1

# default window with an activity alert
set-window-option -g window-status-activity-style bg="#181616",fg=red # bg=bg1, fg=fg3

# active window title colors
set-window-option -g window-status-current-style bg=red,fg="#181616" # fg=bg1

# pane border
set-option -g pane-active-border-style fg="#c4746e" #fg2
set-option -g pane-border-style fg="#181616" #bg1

# message infos
set-option -g message-style bg="#282727",fg="#c5c9c5" # bg=bg2, fg=fg1

# writing commands inactive
set-option -g message-command-style bg="#282727",fg="#c5c9c5" # bg=fg3, fg=bg1

# pane number display
set-option -g display-panes-active-colour "#181616" #fg2
set-option -g display-panes-colour "#181616" #bg1

# Theme settings mixed with colors (unfortunately, but there is no cleaner way)
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left "#[bg=#8ba4b0,fg=#0d0c0c] #S #[bg=#181616,fg=#8ba4b0,nobold,noitalics,nounderscore]"
set-option -g status-right ""

set-window-option -g window-status-current-format "#[bg=#c4746e,fg=#181616,nobold,noitalics,nounderscore]#[bg=#c4746e,fg=#c5c9c5] #I #[bg=#c4746e,fg=#c5c9c5,bold] #W#{?window_zoomed_flag,*Z,} #[bg=#181616,fg=#c4746e,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#282727,fg=#181616,noitalics]#[bg=#282727,fg=#c5c9c5] #I #[bg=#282727,fg=#c5c9c5] #W #[bg=#181616,fg=#282727,noitalics]"
